### ISSUE TITLE
improve credential config

### ISSUE THREAD

**Issue by Jimmy-Xu** [hyperhq/hyper-build-step-plugin#7]
1. change SECRET_KEY to "***********"
2. add a "Test" button, the test run `hyper info` to confirm hyper cli is ready for use.
3. fill the value of ACCESS_KEY and SECRET_KEY when open “Configure System" page.

**Comment by xlgao-zju** [comment]
Ok, 1 and 2 are easy. I need to figure out who to implement 3.

**Comment by xlgao-zju** [comment]
We have moved common functions to a independent [repo](https://github.com/hyperhq/hyper-commons-plugin). And the intended featrues have been implemented in that repo.
